# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\lenovo\Desktop\LPR_2\mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(900, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 900, 21))
        self.menubar.setObjectName("menubar")
        self.menuParkingSystem = QtWidgets.QMenu(self.menubar)
        self.menuParkingSystem.setObjectName("menuParkingSystem")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionPlateRecognition = QtWidgets.QAction(MainWindow)
        self.actionPlateRecognition.setObjectName("actionPlateRecognition")
        self.actionParkingReservation = QtWidgets.QAction(MainWindow)
        self.actionParkingReservation.setObjectName("actionParkingReservation")
        self.actionLogout = QtWidgets.QAction(MainWindow)
        self.actionLogout.setObjectName("actionLogout")
        self.menuParkingSystem.addAction(self.actionPlateRecognition)
        self.menuParkingSystem.addAction(self.actionParkingReservation)
        self.menuParkingSystem.addSeparator()
        self.menuParkingSystem.addAction(self.actionLogout)
        self.menubar.addAction(self.menuParkingSystem.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "停车场预约管理系统"))
        self.menuParkingSystem.setTitle(_translate("MainWindow", "系统"))
        self.actionPlateRecognition.setText(_translate("MainWindow", "车牌识别"))
        self.actionParkingReservation.setText(_translate("MainWindow", "停车场预约"))
        self.actionLogout.setText(_translate("MainWindow", "退出登录"))
